from .final_frame_selector import NODE_CLASS_MAPPINGS as FINAL_FRAME_MAPPINGS
from .final_frame_selector import (
    NODE_DISPLAY_NAME_MAPPINGS as FINAL_FRAME_DISPLAY_MAPPINGS,
)


from .nth_last_frame_selector import NODE_CLASS_MAPPINGS as NTH_LAST_FRAME_MAPPINGS
from .nth_last_frame_selector import (
    NODE_DISPLAY_NAME_MAPPINGS as NTH_LAST_FRAME_DISPLAY_MAPPINGS,
)


from .nth_first_frame_selector import NODE_CLASS_MAPPINGS as NTH_FIRST_FRAME_MAPPINGS
from .nth_first_frame_selector import (
    NODE_DISPLAY_NAME_MAPPINGS as NTH_FIRST_FRAME_DISPLAY_MAPPINGS,
)


from .first_n_frames_selector import NODE_CLASS_MAPPINGS as FIRST_N_FRAMES_MAPPINGS
from .first_n_frames_selector import (
    NODE_DISPLAY_NAME_MAPPINGS as FIRST_N_FRAMES_DISPLAY_MAPPINGS,
)


from .last_n_frames_selector import NODE_CLASS_MAPPINGS as LAST_N_FRAMES_MAPPINGS
from .last_n_frames_selector import (
    NODE_DISPLAY_NAME_MAPPINGS as LAST_N_FRAMES_DISPLAY_MAPPINGS,
)

from .video_merge import NODE_CLASS_MAPPINGS as VIDEO_MERGE_MAPPINGS
from .video_merge import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_MERGE_DISPLAY_MAPPINGS


from .preview_image import NODE_CLASS_MAPPINGS as PREVIEW_IMAGE_MAPPINGS
from .preview_image import NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_IMAGE_DISPLAY_MAPPINGS

from .remove_first_frame import NODE_CLASS_MAPPINGS as REMOVE_FIRST_FRAME_MAPPINGS
from .remove_first_frame import (
    NODE_DISPLAY_NAME_MAPPINGS as REMOVE_FIRST_FRAME_DISPLAY_MAPPINGS,
)


from .remove_first_and_last_frame import (
    NODE_CLASS_MAPPINGS as REMOVE_FIRST_LAST_FRAME_MAPPINGS,
)
from .remove_first_and_last_frame import (
    NODE_DISPLAY_NAME_MAPPINGS as REMOVE_FIRST_LAST_FRAME_DISPLAY_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **FINAL_FRAME_MAPPINGS,
    **NTH_LAST_FRAME_MAPPINGS,
    **NTH_FIRST_FRAME_MAPPINGS,
    **FIRST_N_FRAMES_MAPPINGS,
    **LAST_N_FRAMES_MAPPINGS,
    **VIDEO_MERGE_MAPPINGS,
    **PREVIEW_IMAGE_MAPPINGS,
    **REMOVE_FIRST_FRAME_MAPPINGS,
    **REMOVE_FIRST_LAST_FRAME_MAPPINGS,
}


NODE_DISPLAY_NAME_MAPPINGS = {
    **FINAL_FRAME_DISPLAY_MAPPINGS,
    **NTH_LAST_FRAME_DISPLAY_MAPPINGS,
    **NTH_FIRST_FRAME_DISPLAY_MAPPINGS,
    **FIRST_N_FRAMES_DISPLAY_MAPPINGS,
    **LAST_N_FRAMES_DISPLAY_MAPPINGS,
    **VIDEO_MERGE_DISPLAY_MAPPINGS,
    **PREVIEW_IMAGE_DISPLAY_MAPPINGS,
    **REMOVE_FIRST_FRAME_DISPLAY_MAPPINGS,
    **REMOVE_FIRST_LAST_FRAME_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]