from .final_frame_selector import NODE_CLASS_MAPPINGS as FINAL_FRAME_MAPPINGS
from .final_frame_selector import (
    NODE_DISPLAY_NAME_MAPPINGS as FINAL_FRAME_DISPLAY_MAPPINGS,
)
from .video_merge import NODE_CLASS_MAPPINGS as VIDEO_MERGE_MAPPINGS
from .video_merge import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_MERGE_DISPLAY_MAPPINGS


NODE_CLASS_MAPPINGS = {**FINAL_FRAME_MAPPINGS, **VIDEO_MERGE_MAPPINGS}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FINAL_FRAME_DISPLAY_MAPPINGS,
    **VIDEO_MERGE_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

